import type { ExportData } from '../types.js';

export async function generatePDF(data: ExportData): Promise<Blob> {
	const { jsPDF } = await import('jspdf');
	const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

	const margin = 20;
	const pageW = 210;
	const contentW = pageW - margin * 2;
	let y = margin;

	const line = (text: string, size = 10, bold = false) => {
		doc.setFontSize(size);
		doc.setFont('helvetica', bold ? 'bold' : 'normal');
		const lines = doc.splitTextToSize(text, contentW) as string[];
		doc.text(lines, margin, y);
		y += lines.length * (size * 0.4) + 2;
	};

	const rule = () => {
		doc.setDrawColor(200);
		doc.line(margin, y, pageW - margin, y);
		y += 4;
	};

	const checkPage = () => {
		if (y > 270) {
			doc.addPage();
			y = margin;
		}
	};

	line('taper-track — Taper Summary', 16, true);
	line(`Generated: ${new Date().toLocaleDateString()}`, 9);
	line('This document was created by taper-track, a tracking tool. It is not medical advice.', 8);
	y += 4;
	rule();

	if (data.onboarding) {
		const o = data.onboarding;
		line('Medication', 12, true);
		line(`Class: ${o.medicationClass === 'SSRI' ? 'SSRI / Antidepressant' : 'Benzodiazepine'}`);
		if (o.medicationName) line(`Medication: ${o.medicationName}`);
		line(`Starting dose: ${o.startingDose} ${o.doseUnit}`);
		line(`Taper start: ${o.taperStartDate}`);
		if (o.prescriberEndDate) line(`Target end date: ${o.prescriberEndDate}`);
		if (o.targetFinalDose !== undefined) line(`Target final dose: ${o.targetFinalDose} ${o.doseUnit}`);
		y += 2;
		rule();
	}

	if (data.scheduleEntries.length > 0) {
		line('Taper Schedule', 12, true);
		for (const e of data.scheduleEntries) {
			checkPage();
			line(`${e.changeDate}: ${e.fromDose} mg → ${e.toDose} mg${e.notes ? ` (${e.notes})` : ''}`);
		}
		y += 2;
		rule();
	}

	if (data.symptomLogs.length > 0) {
		line('Symptom Log', 12, true);
		line('Date         Mood  Anxiety  Sleep  Physical symptoms', 9, true);
		for (const l of data.symptomLogs) {
			checkPage();
			const physical = l.physicalSymptoms.length > 0 ? l.physicalSymptoms.join(', ') : '—';
			line(`${l.date}   ${l.mood}/10   ${l.anxiety}/10   ${l.sleepHours}h   ${physical}`, 9);
			if (l.notes) line(`  Notes: ${l.notes}`, 8);
		}
		y += 2;
		rule();
	}

	line('Generated by taper-track — tracking tool only, not medical advice.', 8);

	return doc.output('blob');
}
